### PR TITLE
Fix new user being created/logged in when purchasing a subscription with a different email address

### LINKED ISSUE #119: When logged in, updating email address on checkout creates a new account
### Expected behavior
If updating email address on checkout, new email should should be added to the current customer and no new user account should be created.

### Actual behavior
If email address is changed on checkout a new WP user account and customer is created.

### Steps to reproduce the behavior
1) Be logged in as an existing customer
2) Add a recurring product (recurring may or may not be relevant) to cart
3) Complete purchase, user account should not change.

### Information:
PHP Version: 7

EDD Auto Register Version (or branch): 1.4.3

EDD Version (or branch): 2.11 and 3.0.3

WordPress Version: 6

Any other relevant information:
Auto Register `1.3.14` doesn't have this issue so this appears to have started in `1.4`.

### PR DESCRIPTION
**Pull request by robincornett**
Fixes #119

Proposed Changes:
1. Updates the shimmed payment in `get_payment` to get the user ID if it's included in the user data.
2. Updates `can_create_user` to return false if the payment object already has a user ID assigned.
3. Updates assigning the user ID to the order/payment so that the order object is updated directly in EDD 3.0, leaving the payment meta to be updated in 2.x.

### CODE REVIEW

**Review by cklosowski — APPROVED** [review]

**Comment by cklosowski** [comment]
@mihaijoldis @dgoldak @zkawesome I've tested this but as it's something that we want to ensure we get right, I'd appreciate multiple people testing and approving. 

I've put this on the EDD site over the weekend for testing as well.

**Comment by robincornett** [comment]
Hold off--Free Downloads doesn't use the `edd_built_order` hook so it's not working for that extension in 3.0.

**Comment by cklosowski** [comment]
Yep seems to work fine for EDD Free Downloads!

**Review by cklosowski — APPROVED** [review]

**Review by mihaijoldis — APPROVED** [review]

**Comment by dgoldak** [comment]
@robincornett with Recurring + Auto Register w/Limit Auto Register enabled using a 100% discount code making the purchase free. This causes "Error: You must be logged in to purchase a subscription".

**Comment by robincornett** [comment]
Hi @dgoldak that's a known issue right now with the "Limit Auto Register" setting and offsite payment gateways. We're adding a warning in the settings for now: https://github.com/awesomemotive/edd-auto-register/issues/114. At the point that Recurring engages with Auto Register and an offsite gateway, the order is still pending.

**Review by dgoldak — APPROVED** [review]

**Pull request merged**
