### PR TITLE
Add users when batch inserting payments

### LINKED ISSUE #33: Make Auto Register work for CSV Payment Imports
People who are migrating payments from 1 domain to another will likely want to have their users migrated as well. A good way to do this would be to have Auto Register create the WordPress users when the payments are created during the CSV import. 

However, currently, it does not create the users upon CSV import because of these 2 things:

https://github.com/easydigitaldownloads/edd-auto-register/blob/9806021e969d211a339aff70dfa53eec963971a9/edd-auto-register.php#L293

https://github.com/easydigitaldownloads/edd-auto-register/blob/master/edd-auto-register.php#L314

Proposal: Make Users get Auto Registered when creating payments if it is being done through CSV Payment Import

### PR DESCRIPTION
**Pull request by robincornett**
Fixes #33

Proposed Changes:
1. Initially, this recreated the work from 126b9cc.
2. In 3945de7, since we were using the `edd_payment_saved` hook twice, I removed the new use of it and moved the batch import check and user creation to inside the existing function. Without this, the `maybe_insert_user` method was actually assigning my logged in user ID to every payment.
3. Currently missing: the "Verify your account" email is still sending and I've not figured that one out yet. Possibly we need to manually delete the user meta for `_edd_pending_verification` during this process.

### CODE REVIEW

**Comment by cklosowski** [comment]
@robincornett I'm seeing something that we are also seeing on `release/1.4` (so likely `master`). Imported payments all have a user ID of `1`. So this check:
```
		public function create_user( $deprecated = array(), $payment_id = 0 ) {

			$payment = new EDD_Payment( $payment_id );

			// User account already associated
			if ( $payment->user_id > 0 ) {
				return false;
			}
```

Always returns and doesn't create a new user.

Here is my CSV file to test with:
```
"Email","First Name","Last Name","Address","Address (Line 2)","City","State","Country","Zip / Postal Code","Products (Verbose)","Products (Raw)","Amount ($)","Tax ($)","Discount Code","Payment Method","Transaction ID","Purchase Key","Date","User","Currency","IP Address","Mode (Live|Test)","Status","Country Name"
"importeduser2@edd.lndo.site","Imported","Klosowski","","","","","","","Testing fix file upload -  - $10.00","Testing fix file upload|10{0}{0}","10.00","0.00","none","Test Payment","1731835","imported-1fe590d1f5e4a07c4a16893ee26f028a","2022-03-01 20:42:43","admin","USD","172.20.0.1","test","complete",""
```

It creates a new EDD customer, but you'll see that this customer is assigned to User ID 1 (my admin user that I'm using to import) and in the payment meta, `1` is set as well:
image

image

**Comment by robincornett** [comment]
@cklosowski your sample data has `admin` as a username in it already--so the EDD importer will assign the order/customer to you. I think it should be empty or have a username that doesn't exist. If I have a username that doesn't exist in there, it's ignored and the email address is used for the user, but if the username does exist, it will be assigned to that user.

**Comment by cklosowski** [comment]
@robincornett Sorry about that, I thought I had removed all the user specific items out. I’ll give it another go.

**Comment by cklosowski** [comment]
@robincornett We've created a merge conflict here that needs resolving before we can put this into the release branch, related to the changing of using `$payment` and the new `can_create_user` method.

**Pull request merged**
